### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by bfirsh**
Signed-off-by: Ben Firshman ben@firshman.co.uk

### CODE REVIEW

**Comment by toli** [comment]
LGTM

**Comment by tianon** [comment]
LGTM, although I'll admit I'm not a huge fan of how verbose Apache is

cc @ehazlett

**Comment by ehazlett** [comment]
yeah something like BSD or MIT would be preferred but since B2D (legacy) and Docker are Apache 2.0 I think we should match.

LGTM

**Comment by bfirsh** [comment]
@tianon @ehazlett [Our lawyers actually insist on Apache 2.](https://github.com/docker/compose/commit/3a2c9c1016a3e0929f13b34ef69e0abe9494aa7d) Apparently BSD/MIT isn't legally airtight enough.

**Pull request merged**
